### ISSUE TITLE
No entry or class found for 'webman-ffmpeg'

### ISSUE THREAD

**Issue by wahyuief** [brooke1220/webman-ffmpeg#1]
I get an error like this when I use `FFMpeg::openUrl('https://videocoursebuilder.com/lesson-1.mp4');`

`DI\NotFoundException: No entry or class found for 'webman-ffmpeg' in \webman\vendor\php-di\php-di\src\Container.php:136
Stack trace:
#0 \webman\vendor\brooke1220\webman-ffmpeg\src\Support\Container.php(31): DI\Container->get('webman-ffmpeg')
#1 \webman\vendor\brooke1220\webman-ffmpeg\src\Support\FFMpeg.php(19): Brooke1220\WebmanFfmpeg\Support\Container::__callStatic('get', Array)
#2 \webman\vendor\brooke1220\webman-ffmpeg\src\Support\FFMpeg.php(24): Brooke1220\WebmanFfmpeg\Support\FFMpeg::instance()
#3 \webman\app\controller\IndexController.php(12): Brooke1220\WebmanFfmpeg\Support\FFMpeg::__callStatic('openUrl', Array)
#4 \webman\vendor\workerman\webman-framework\src\App.php(318): app\controller\IndexController->index(Object(support\Request))
#5 \webman\vendor\workerman\webman-framework\src\App.php(167): Webman\App::Webman\{closure}(Object(support\Request))
#6 \webman\vendor\workerman\workerman\Connection\TcpConnection.php(646): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#7 \webman\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #156)
#8 \webman\vendor\workerman\workerman\Worker.php(2470): Workerman\Events\Select->loop()
#9 \webman\vendor\workerman\workerman\Worker.php(1453): Workerman\Worker->run()
#10 \webman\vendor\workerman\workerman\Worker.php(1396): Workerman\Worker::forkWorkersForWindows()
#11 \webman\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()
#12 \webman\vendor\workerman\webman-framework\src\support\App.php(131): Workerman\Worker::runAll()
#13 \webman\start.php(4): support\App::run()
#14 {main}`

**Comment by wahyuief** [comment]
Solved! Everything works

Requirements
PhpOption `composer require phpoption/phpoption`
PHP Dotenv `composer require vlucas/phpdotenv`
League FlySystem `composer require league/flysystem:^v1.1`

Solved by copying \config\plugin\brooke1220\webman-ffmpeg\dependence.php to \config\dependence.php
